"use server";

import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { canPlatform, getEffectiveAccess } from "@/lib/rbac";
import { revalidatePath } from "next/cache";
import { headers } from "next/headers";
import crypto from "crypto";

function randomTempPassword() {
  return crypto.randomBytes(9).toString("base64").replace(/[+/=]/g, "x") + "!1";
}
function randomToken(bytes = 24) {
  return crypto.randomBytes(bytes).toString("base64url");
}

export async function createCompany(formData: FormData) {
  const companyName = (formData.get("companyName") as string | null)?.trim();
  const notifyPrefix = (formData.get("notifyPrefix") as string | null)?.trim() || null;
  const mode = ((formData.get("mode") as string | null) || "none") as "none" | "direct" | "invite";
  const adminName = (formData.get("adminName") as string | null)?.trim() || null;
  const adminEmail = (formData.get("adminEmail") as string | null)?.trim() || null;
  const adminPassword = (formData.get("adminPassword") as string | null)?.trim() || null;

  if (!companyName) {
    return { error: "Company name is required." };
  }
  if (mode !== "none") {
    if (!adminEmail) return { error: "Admin email is required for this onboarding option." };
    if (!adminName) return { error: "Admin name is required for this onboarding option." };
    if (mode === "direct" && adminPassword && adminPassword.length < 6) {
      return { error: "Password must be at least 6 characters." };
    }
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated." };

  // Authorization check — everything below uses the service-role client,
  // which bypasses RLS entirely, so this check IS the security boundary
  // for this action.
  const access = await getEffectiveAccess(supabase, user.id);
  if (!canPlatform(access, "platform.manage_companies")) {
    return { error: "Only a platform admin can do this." };
  }
  if (mode !== "none" && !canPlatform(access, "company.onboard_admin")) {
    return { error: "Only a platform admin can onboard a company's admin." };
  }

  const admin = createAdminClient();

  const { data: company, error: companyError } = await admin
    .from("companies")
    .insert({ name: companyName, notify_prefix: notifyPrefix, created_by: user.id })
    .select("id, name")
    .single();
  if (companyError || !company) {
    return { error: companyError?.message ?? "Could not create company." };
  }

  await admin.from("admin_audit_log").insert({
    actor_id: user.id,
    org_id: company.id,
    action: "company.create",
    target_type: "company",
    target_id: company.id,
    details: { name: companyName },
  });

  if (mode === "none" || !adminEmail || !adminName) {
    revalidatePath("/platform");
    return { error: null, company };
  }

  // The companies AFTER INSERT trigger seeds this company's starter
  // roles (Company Admin / Supervisor / Inspector / Auditor) — fetch the
  // Company Admin one to link the new admin to it.
  const { data: adminRole, error: adminRoleError } = await admin
    .from("roles")
    .select("id")
    .eq("org_id", company.id)
    .eq("system_key", "company_admin")
    .single();
  if (adminRoleError || !adminRole) {
    return {
      error: `Company created, but its starter roles weren't found (has the roles/permissions migration been run?): ${adminRoleError?.message ?? "unknown error"}`,
      company,
    };
  }

  if (mode === "invite") {
    const token = randomToken();
    const { error: inviteError } = await admin.from("invites").insert({
      org_id: company.id,
      email: adminEmail,
      full_name: adminName,
      role_id: adminRole.id,
      mode: "self_service",
      token,
      invited_by: user.id,
    });
    if (inviteError) {
      return {
        error: `Company created, but the invite could not be created: ${inviteError.message}`,
        company,
      };
    }

    await admin.from("admin_audit_log").insert({
      actor_id: user.id,
      org_id: company.id,
      action: "user.invite",
      target_type: "invite",
      target_id: null,
      details: { email: adminEmail, role_id: adminRole.id },
    });

    const hdrs = await headers();
    const host = hdrs.get("host") ?? "localhost:3000";
    const protocol = host.startsWith("localhost") ? "http" : "https";
    const acceptUrl = `${protocol}://${host}/accept-invite/${token}`;

    revalidatePath("/platform");
    return { error: null, company, invite: { email: adminEmail, acceptUrl } };
  }

  // mode === "direct"
  const wasAutoGenerated = !adminPassword;
  const tempPassword = adminPassword || randomTempPassword();
  const { data: created, error: createUserError } = await admin.auth.admin.createUser({
    email: adminEmail,
    password: tempPassword,
    email_confirm: true,
    user_metadata: { full_name: adminName },
  });
  if (createUserError || !created?.user) {
    return {
      error: `Company created, but the admin account could not be created: ${createUserError?.message ?? "unknown error"}`,
      company,
    };
  }

  const newUserId = created.user.id;
  const { error: profileError } = await admin
    .from("profiles")
    .update({
      org_id: company.id,
      role_id: adminRole.id,
      must_change_password: wasAutoGenerated,
      full_name: adminName,
    })
    .eq("id", newUserId);
  if (profileError) {
    return {
      error: `Company and admin login created, but linking the admin to the company failed: ${profileError.message}`,
      company,
    };
  }

  await admin.from("admin_audit_log").insert({
    actor_id: user.id,
    org_id: company.id,
    action: "user.create_direct",
    target_type: "user",
    target_id: newUserId,
    details: { email: adminEmail, role_id: adminRole.id },
  });

  revalidatePath("/platform");
  return {
    error: null,
    company,
    admin: { email: adminEmail, tempPassword, wasAutoGenerated },
  };
}
