"use client";

import { useState, useTransition } from "react";
import { createCompany } from "./actions";

type Mode = "none" | "direct" | "invite";

export default function NewCompanyForm() {
  const [companyName, setCompanyName] = useState("");
  const [notifyPrefix, setNotifyPrefix] = useState("");
  const [mode, setMode] = useState<Mode>("none");
  const [adminName, setAdminName] = useState("");
  const [adminEmail, setAdminEmail] = useState("");
  const [adminPassword, setAdminPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [directResult, setDirectResult] = useState<
    { email: string; tempPassword: string; wasAutoGenerated: boolean } | null
  >(null);
  const [inviteResult, setInviteResult] = useState<{ email: string; acceptUrl: string } | null>(null);
  const [pending, startTransition] = useTransition();

  const reset = () => {
    setCompanyName("");
    setNotifyPrefix("");
    setMode("none");
    setAdminName("");
    setAdminEmail("");
    setAdminPassword("");
  };

  const submit = () => {
    if (!companyName.trim()) return;
    setError(null);
    setDirectResult(null);
    setInviteResult(null);
    const formData = new FormData();
    formData.set("companyName", companyName.trim());
    formData.set("notifyPrefix", notifyPrefix.trim());
    formData.set("mode", mode);
    formData.set("adminName", adminName.trim());
    formData.set("adminEmail", adminEmail.trim());
    formData.set("adminPassword", adminPassword);
    startTransition(async () => {
      const res = await createCompany(formData);
      if (res?.error) setError(res.error);
      if (res?.admin) setDirectResult(res.admin);
      if (res?.invite) setInviteResult(res.invite);
      if (!res?.error) reset();
    });
  };

  return (
    <div className="bg-white border rounded-xl p-5" style={{ borderColor: "var(--ch-line)" }}>
      <div className="grid gap-3 sm:grid-cols-2 mb-3">
        <input
          className="border rounded-lg px-3 py-2 text-sm"
          style={{ borderColor: "var(--ch-line)" }}
          placeholder="Company name"
          value={companyName}
          onChange={(e) => setCompanyName(e.target.value)}
        />
        <input
          className="border rounded-lg px-3 py-2 text-sm"
          style={{ borderColor: "var(--ch-line)" }}
          placeholder="Notification email prefix, e.g. AHM (optional)"
          value={notifyPrefix}
          onChange={(e) => setNotifyPrefix(e.target.value)}
        />
      </div>
      <p className="text-xs mb-3" style={{ color: "var(--ch-sub)" }}>
        Reminder emails for this company will come from{" "}
        <strong>{(notifyPrefix.trim() || companyName.trim().split(/\s+/)[0] || "…").toUpperCase()}.notification@aifexis.com</strong>
        . Leave blank to derive it from the company name.
      </p>

      <div
        className="text-xs font-semibold uppercase tracking-wide mb-2"
        style={{ color: "var(--ch-sub)" }}
      >
        Onboard an admin?
      </div>
      <div className="flex gap-4 flex-wrap mb-3 text-sm" style={{ color: "var(--ch-ink)" }}>
        <label className="flex items-center gap-1.5">
          <input type="radio" checked={mode === "none"} onChange={() => setMode("none")} /> Not now
        </label>
        <label className="flex items-center gap-1.5">
          <input type="radio" checked={mode === "direct"} onChange={() => setMode("direct")} /> Create
          login now
        </label>
        <label className="flex items-center gap-1.5">
          <input type="radio" checked={mode === "invite"} onChange={() => setMode("invite")} /> Send
          invite link
        </label>
      </div>

      {mode !== "none" && (
        <div className="grid gap-3 sm:grid-cols-2 mb-1">
          <input
            className="border rounded-lg px-3 py-2 text-sm"
            style={{ borderColor: "var(--ch-line)" }}
            placeholder="Admin full name"
            value={adminName}
            onChange={(e) => setAdminName(e.target.value)}
          />
          <input
            className="border rounded-lg px-3 py-2 text-sm"
            style={{ borderColor: "var(--ch-line)" }}
            placeholder="Admin email"
            type="email"
            value={adminEmail}
            onChange={(e) => setAdminEmail(e.target.value)}
          />
          {mode === "direct" && (
            <input
              className="border rounded-lg px-3 py-2 text-sm sm:col-span-2"
              style={{ borderColor: "var(--ch-line)" }}
              placeholder="Password (leave blank to auto-generate one)"
              type="text"
              value={adminPassword}
              onChange={(e) => setAdminPassword(e.target.value)}
            />
          )}
        </div>
      )}

      <p className="text-xs mt-2 mb-3" style={{ color: "var(--ch-sub)" }}>
        {mode === "none" && "You can onboard an admin for this company later."}
        {mode === "direct" &&
          "Creates the login immediately — set your own password above, or leave it blank to get a one-time temporary password to hand off."}
        {mode === "invite" &&
          "Generates a one-time invite link — the admin sets their own password when they open it."}
      </p>

      <button
        onClick={submit}
        disabled={pending || !companyName.trim()}
        className="ch-btn-primary rounded-lg px-4 py-2 text-sm font-semibold disabled:opacity-50"
      >
        {pending ? "Adding…" : "Add company"}
      </button>

      {error && (
        <div
          className="text-sm mt-3 rounded-lg px-3 py-2"
          style={{ background: "var(--ch-fail-bg)", color: "var(--ch-fail)" }}
        >
          {error}
        </div>
      )}
      {directResult && (
        <div
          className="text-sm mt-3 rounded-lg px-3 py-2"
          style={{ background: "var(--ch-pass-bg)", color: "var(--ch-pass)" }}
        >
          Admin account created for <strong>{directResult.email}</strong>.
          <br />
          {directResult.wasAutoGenerated ? "Temporary" : "Set"} password:{" "}
          <strong>{directResult.tempPassword}</strong>
          <br />
          <span style={{ color: "var(--ch-ink)" }}>
            Share this with them now — it won&apos;t be shown again.
          </span>
        </div>
      )}
      {inviteResult && (
        <div
          className="text-sm mt-3 rounded-lg px-3 py-2 break-all"
          style={{ background: "var(--ch-pass-bg)", color: "var(--ch-pass)" }}
        >
          Invite created for <strong>{inviteResult.email}</strong>.
          <br />
          Link: <strong>{inviteResult.acceptUrl}</strong>
          <br />
          <span style={{ color: "var(--ch-ink)" }}>Send them this link — it expires in 7 days.</span>
        </div>
      )}
    </div>
  );
}
