"use server";

import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { can, canAssignRole, getEffectiveRole } from "@/lib/rbac";
import { revalidatePath } from "next/cache";
import { headers } from "next/headers";
import crypto from "crypto";

function randomTempPassword() {
  return crypto.randomBytes(9).toString("base64").replace(/[+/=]/g, "x") + "!1";
}
function randomToken(bytes = 24) {
  return crypto.randomBytes(bytes).toString("base64url");
}

export async function inviteTeamMember(formData: FormData) {
  const name = (formData.get("name") as string | null)?.trim();
  const email = (formData.get("email") as string | null)?.trim();
  const role = (formData.get("role") as string | null)?.trim();
  const mode = ((formData.get("mode") as string | null) || "invite") as "direct" | "invite";
  const password = (formData.get("password") as string | null)?.trim() || null;

  if (!name) return { error: "Name is required." };
  if (!email) return { error: "Email is required." };
  if (mode === "direct" && password && password.length < 6) {
    return { error: "Password must be at least 6 characters." };
  }

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated." };

  const { role: callerRole, orgId } = await getEffectiveRole(supabase, user.id);

  // Authorization check — everything below uses the service-role client,
  // which bypasses RLS entirely, so this check IS the security boundary
  // for this action. Both the action itself and the specific role being
  // handed out go through the rbac matrix — never a raw string compare.
  if (!can(callerRole, "team.invite") || !orgId) {
    return { error: "Only a company admin can do this." };
  }
  if (!role || !canAssignRole(callerRole, role)) {
    return { error: "Choose a valid role." };
  }

  const admin = createAdminClient();

  if (mode === "invite") {
    const token = randomToken();
    const { error: inviteError } = await admin.from("invites").insert({
      org_id: orgId,
      email,
      full_name: name,
      role,
      mode: "self_service",
      token,
      invited_by: user.id,
    });
    if (inviteError) return { error: inviteError.message };

    await admin.from("admin_audit_log").insert({
      actor_id: user.id,
      org_id: orgId,
      action: "user.invite",
      target_type: "invite",
      target_id: null,
      details: { email, role },
    });

    const hdrs = await headers();
    const host = hdrs.get("host") ?? "localhost:3000";
    const protocol = host.startsWith("localhost") ? "http" : "https";
    const acceptUrl = `${protocol}://${host}/accept-invite/${token}`;

    revalidatePath("/team");
    return { error: null, invite: { email, acceptUrl } };
  }

  // mode === "direct"
  const wasAutoGenerated = !password;
  const tempPassword = password || randomTempPassword();
  const { data: created, error: createUserError } = await admin.auth.admin.createUser({
    email,
    password: tempPassword,
    email_confirm: true,
    user_metadata: { full_name: name },
  });
  if (createUserError || !created?.user) {
    return { error: createUserError?.message ?? "Could not create the account." };
  }

  const newUserId = created.user.id;
  const { error: profileError } = await admin
    .from("profiles")
    .update({ org_id: orgId, role, must_change_password: wasAutoGenerated, full_name: name })
    .eq("id", newUserId);
  if (profileError) return { error: profileError.message };

  await admin.from("admin_audit_log").insert({
    actor_id: user.id,
    org_id: orgId,
    action: "user.create_direct",
    target_type: "user",
    target_id: newUserId,
    details: { email, role },
  });

  revalidatePath("/team");
  return { error: null, admin: { email, tempPassword, wasAutoGenerated } };
}

export async function setUserStatus(userId: string, status: "active" | "inactive") {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated." };
  if (userId === user.id) return { error: "You can't deactivate your own account." };

  const { role: callerRole, orgId } = await getEffectiveRole(supabase, user.id);
  if (!can(callerRole, "team.manage_status") || !orgId) {
    return { error: "Only a company admin can do this." };
  }

  const { data: target } = await supabase
    .from("profiles")
    .select("org_id")
    .eq("id", userId)
    .single();
  if (!target || target.org_id !== orgId) {
    return { error: "That user isn't in your company." };
  }

  // A genuine company_admin acting on an existing member of their own
  // company satisfies both RLS and the profile guard trigger directly —
  // no need for the service-role client here.
  const { error } = await supabase.from("profiles").update({ status }).eq("id", userId);
  if (error) return { error: error.message };

  revalidatePath("/team");
  return { error: null };
}
