"use client";

import { useState, useTransition } from "react";
import { inviteTeamMember } from "./actions";
import { ROLE_LABELS, type TenantRole } from "@/lib/rbac";

type Mode = "direct" | "invite";

export default function NewMemberForm({ roleOptions }: { roleOptions: readonly TenantRole[] }) {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [role, setRole] = useState<TenantRole>(roleOptions[0] ?? "inspector");
  const [mode, setMode] = useState<Mode>("invite");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [directResult, setDirectResult] = useState<
    { email: string; tempPassword: string; wasAutoGenerated: boolean } | null
  >(null);
  const [inviteResult, setInviteResult] = useState<{ email: string; acceptUrl: string } | null>(null);
  const [pending, startTransition] = useTransition();

  const reset = () => {
    setName("");
    setEmail("");
    setRole(roleOptions[0] ?? "inspector");
    setPassword("");
  };

  const submit = () => {
    if (!name.trim() || !email.trim()) return;
    setError(null);
    setDirectResult(null);
    setInviteResult(null);
    const formData = new FormData();
    formData.set("name", name.trim());
    formData.set("email", email.trim());
    formData.set("role", role);
    formData.set("mode", mode);
    formData.set("password", password);
    startTransition(async () => {
      const res = await inviteTeamMember(formData);
      if (res?.error) setError(res.error);
      if (res?.admin) setDirectResult(res.admin);
      if (res?.invite) setInviteResult(res.invite);
      if (!res?.error) reset();
    });
  };

  return (
    <div className="bg-white border rounded-xl p-5" style={{ borderColor: "var(--ch-line)" }}>
      <div className="grid gap-3 sm:grid-cols-2">
        <input
          className="border rounded-lg px-3 py-2 text-sm"
          style={{ borderColor: "var(--ch-line)" }}
          placeholder="Full name"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
        <input
          className="border rounded-lg px-3 py-2 text-sm"
          style={{ borderColor: "var(--ch-line)" }}
          placeholder="Email"
          type="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
        />
      </div>

      <div className="flex items-center gap-4 flex-wrap mt-3 mb-3 text-sm" style={{ color: "var(--ch-ink)" }}>
        <label className="flex items-center gap-1.5">
          Role
          <select
            className="border rounded-lg px-2 py-1.5 text-sm ml-1"
            style={{ borderColor: "var(--ch-line)" }}
            value={role}
            onChange={(e) => setRole(e.target.value as TenantRole)}
          >
            {roleOptions.map((r) => (
              <option key={r} value={r}>
                {ROLE_LABELS[r]}
              </option>
            ))}
          </select>
        </label>

        <label className="flex items-center gap-1.5">
          <input type="radio" checked={mode === "invite"} onChange={() => setMode("invite")} /> Send
          invite link
        </label>
        <label className="flex items-center gap-1.5">
          <input type="radio" checked={mode === "direct"} onChange={() => setMode("direct")} /> Create
          login now
        </label>
      </div>

      {mode === "direct" && (
        <input
          className="w-full border rounded-lg px-3 py-2 text-sm mb-3"
          style={{ borderColor: "var(--ch-line)" }}
          placeholder="Password (leave blank to auto-generate one)"
          type="text"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
      )}

      <p className="text-xs mb-3" style={{ color: "var(--ch-sub)" }}>
        {mode === "invite"
          ? "Generates a one-time invite link — they set their own password when they open it."
          : "Creates the login immediately — set your own password above, or leave it blank to get a one-time temporary password to hand off."}
      </p>

      <button
        onClick={submit}
        disabled={pending || !name.trim() || !email.trim()}
        className="ch-btn-primary rounded-lg px-4 py-2 text-sm font-semibold disabled:opacity-50"
      >
        {pending ? "Adding…" : "Add team member"}
      </button>

      {error && (
        <div
          className="text-sm mt-3 rounded-lg px-3 py-2"
          style={{ background: "var(--ch-fail-bg)", color: "var(--ch-fail)" }}
        >
          {error}
        </div>
      )}
      {directResult && (
        <div
          className="text-sm mt-3 rounded-lg px-3 py-2"
          style={{ background: "var(--ch-pass-bg)", color: "var(--ch-pass)" }}
        >
          Account created for <strong>{directResult.email}</strong>.
          <br />
          {directResult.wasAutoGenerated ? "Temporary" : "Set"} password:{" "}
          <strong>{directResult.tempPassword}</strong>
          <br />
          <span style={{ color: "var(--ch-ink)" }}>
            Share this with them now — it won&apos;t be shown again.
          </span>
        </div>
      )}
      {inviteResult && (
        <div
          className="text-sm mt-3 rounded-lg px-3 py-2 break-all"
          style={{ background: "var(--ch-pass-bg)", color: "var(--ch-pass)" }}
        >
          Invite created for <strong>{inviteResult.email}</strong>.
          <br />
          Link: <strong>{inviteResult.acceptUrl}</strong>
          <br />
          <span style={{ color: "var(--ch-ink)" }}>Send them this link — it expires in 7 days.</span>
        </div>
      )}
    </div>
  );
}
